accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    
]

blogs/urls.py
from django.urls import path
from blogs.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView 

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/create/", BlogCreateView.as_view(), name="create"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", BlogUpdateView.as_view(), name="update"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="delete")
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blogs.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")), 
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=120)
    body = models.TextField()
    author = models.ForeignKey(
    "auth.User",
    on_delete = models.CASCADE,
    #Si se elimina el autor, se eliminara todo el contenido de ese autorJ
)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse ("post_detail", args=[str(self.id)])
    #reverse("post_detail", args=[str(self.id)])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy  #Reverse_lazy aterrizar en un sitio especifico
from django.views.generic import CreateView

# Create your views here.
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blogs/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Post
from django.urls import reverse_lazy


# Create your views here.
class BlogListView(ListView):
    model = Post
    template_name = "home.html"

class BlogCreateView(CreateView):
        model = Post
        template_name = "post_new.html"
        fields = ["title", "author", "body"]

class BlogDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"

class BlogUpdateView(UpdateView):
    model = Post
    template_name = "update.html"
    fields = ["title", "body"]

class BlogDeleteView(DeleteView):
    model = Post
    template_name = "delete.html"
    success_url = reverse_lazy("home")

    """ El succes url ubica donde caera el usuario luego de la accion """

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Cocadas</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header>
        <h1><a href="{% url 'home' %}">Blog Cocadas</a></h1>
    </header>
    
    <div>
        <a href="{% url 'create' %}">New post</a>
    </div>

    {% block content %}

    {% endblock content %}
</body>
</html>

templates/delete.html
{% extends "_base.html" }

{% block content %}
    <h1> Post Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Estas seguro que quieres borrar {{ post.tittle }}</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

templates/home.html
{% extends "_base.html" %}

{% block content %}

    {% if user.is_authenticated %}
        Epale {{ user.username}}    
        <form action="{% url 'logout' %}" method="post"> {% csrf_token %}
            <button type="submit">Log Out</button>
        </form>
        
    {% else %}
        <p>No estas registrado</p>
        <a href="{% url 'login' %}">Log in</a>
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}

    {% for post in post_list %}
        <ul>
            <li>
                <a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a>
            </li>
        </ul>
    {% endfor %}
{% endblock content %}

templates/post_detail.html
{% extends "_base.html" %}
{% block content %}
    <h2>{{ post.title }}</h2>
    <p> {{ post.body }} </p>
    <a href=" {% url 'update' post.pk %}">Edit</a>
    <a href="{% url 'delete' post.pk %}">Delete</a>
    {% endblock content %}

templates/post_new.html
{% extends "_base.html" %}


{% block content %}
    <h1>New post</h1>
    <form action="" method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    
{% endblock content %}

templates/update.html
{% extends "_base.html" %}

{% block content %}
    <h1>Edit post</h1>
    <form action="" method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
    {% endblock content %}